### ISSUE TITLE
Questions about Figure 1.

### ISSUE THREAD

**Issue by CannotBeFatAnyMore** [Gavinwxy/DGCL#11]
Thanks for your brilliant work, I tried to comprehensive Fig1.a, but I cannot find out the method you draw this picture? Is It t-SNE?
![image](https://github.com/Gavinwxy/DGCL/assets/67741279/04791a58-4b5d-4f6b-9763-0dbfe31186cb)

**Comment by gavinwxy** [comment]
Thanks for your interest. Yes, I used TSNE from sklearn library on the pre-collected pixel-wise features to draw this picture.
